const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 800;

const GAME_WIDTH = 300;
const GAME_HEIGHT = 600;

const FPS = 60;
const GAME_SPEED = 100;

const LINE_SPACING = 40;

const TEXT_PUZZLE_FONT = "30px Roboto"
const DEFAULT_IMAGE_PUZZLE_WIDTH = 100
const DEFAULT_IMAGE_PUZZLE_HEIGHT = 100

const IMAGE_TYPE = 'image'
const TEXT_TYPE = 'text'

const QUESTION_TOP_SPACING = 100
const QUESTION_GUTTER = 100;
const QUESTION_LEFT_SPACING = 100

const ANSWER_TOP_SPACING = 100;
const ANSWER_RIGHT_SPACING = 10;
const ANSWER_GUTTER = 100;

const GAME_START = 'BAT_DAU'
const GAME_OVER = 'GAME_OVER'
const WIN = 'WIN'

const RESTART = 'CHOI_LAI'
const RESET = 'RESET'
const PAUSE = 'PAUSE'